export const ROLES = {
  IT_ADMIN: "IT_ADMIN",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DEVELOPER: "DEVELOPER",
  TESTER: "TESTER",
};

export const PROJECT_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  UNDER_TESTING: "UNDER_TESTING",
  TESTING_COMPLETED: "TESTING_COMPLETED",
  APPROVED: "APPROVED"
};

export const MODULE_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

export const WORKLOG_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

export const PRIORITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW"
};

export const RATING_DECISION = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

export const PERFORMANCE_METRICS = {
  MAX_SCORE: 10,
  DEADLINE_PENALTY: 0.5,
  REJECTION_PENALTY: -1
};