export const ROLES = {
  IT_ADMIN: "IT_ADMIN",
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DEVELOPER: "DEVELOPER",
  TESTER: "TESTER",
};

export const PROJECT_STATUS = {
 PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  IN_PROGRESS: "IN_PROGRESS",
  UNDER_TESTING: "UNDER_TESTING",
  TESTING_COMPLETED: "TESTING_COMPLETED"
};

export const MODULE_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  IN_PROGRESS: "IN_PROGRESS"
};

export const TASK_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  IN_PROGRESS: "IN_PROGRESS"
};

export const REVIEW_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
}

export const WORKLOG_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};
